fix bug with error in calc

diff --git a/calc b/calc
--- a/calc
+++ b/calc
@@ -1,9 +1,14 @@
 #!/bin/bash
+if [[ $1 != "sum" ]] && [[ $1 != "sub" ]] && [[ $1 != "mul" ]] && [[ $1 != "div" ]]
+    then
+    echo "Error: operation not found" >&2
+    exit -1
+fi
 
 if ! [[ $2 =~ ^-?[0-9]+$ ]] || ! [[ $3 =~ ^-?[0-9]+$ ]]
     then
     echo "Error: third and fourth argument must be integer numbers" >&2
-    exit -1
+    exit -2
 fi
 
 case $1 in
@@ -12,9 +17,11 @@ case $1 in
 "mul") echo $[ $2 * $3 ];;
 "div") if [ $3 -eq 0 ]
        then echo "Error: division by zero" >&2
+       exit -3
        else echo $[ $2 / $3 ]
        fi
        ;;
 
-*) echo "Error: operation not found" >&2;;
+#*) echo "Error: operation not found" >&2
+#exit -3;;
 esac
