fixed

diff --git a/exit b/exit
--- a/exit
+++ b/exit
@@ -3,9 +3,10 @@
 if [ -z $1 ]
   then
   exit 0
-elif [[ $1 =~ ^[0-9]+$ ]]
+elif [[ $1 =~ ^-?[0-9]+$ ]]
   then
   exit $1
 else
-  echo "Error: invalid return code"
+  echo "Error: invalid return code" >&2
+exit -7
 fi
diff --git a/reverse b/reverse
--- a/reverse
+++ b/reverse
@@ -1,3 +1,9 @@
 #!/bin/bash
 
-tac $2 > $3
+if ![[ -f $1 ]]
+then
+echo "Error: no such file" >&2
+exit -6
+fi
+
+tac $1 > $2
