fixed

diff --git a/main b/main
--- a/main
+++ b/main
@@ -3,27 +3,55 @@
 ./filecheck
 
 if [[ "$1" = "calc" ]]
-then
-./calc $2 $3 $4
-elif [[ "$1" = "search" ]]
-then
-./search $2 $3
-elif [[ "$1" = "reverse" ]]
-then
-./reverse $2 $3
-elif [[ "$1" = "strlen" ]]
-then
-./strlen $2
-elif [[ "$1" = "log" ]]
-then
-./log
-elif [[ "$1" = "exit" ]]
-then
-./exit
-elif [[ "$1" = "help" ]]
-then
-./help
-elif [[ "$1" = "interactive" ]]
-then
-./menu
+   then
+   if [[ "$#" -eq 4 ]]
+      then
+      ./calc $2 $3 $4
+   else
+   echo "Error: not enough arguments" >&2
+   exit -10
+   fi
+   elif [[ "$1" = "search" ]]
+      then
+      if [[ "$#" -eq 3 ]]
+         then
+         ./search $2 $3
+      else
+      echo "Error: not enough arguments" >&2
+      exit -10
+      fi
+      elif [[ "$1" = "reverse" ]]
+         then
+         if [[ "$#" -eq 3 ]]
+             then
+             ./reverse $2 $3
+         else
+         echo "Error: not enough arguments" >&2
+         exit -10
+         fi
+         elif [[ "$1" = "strlen" ]]
+             then
+             if [[ "$#" -eq 2 ]]
+                 then
+                 ./strlen $2
+              else
+              echo "Error: not enough arguments" >&2
+              exit -10
+              fi
+              elif [[ "$1" = "log" ]]
+                  then
+                  ./log
+              elif [[ "$1" = "exit" ]]
+                  then
+                  ./exit $2
+                  exit $2
+              elif [[ "$1" = "help" ]]
+                  then
+                  ./help
+              elif [[ "$1" = "interactive" ]]
+                  then
+                  ./menu
+              else
+              echo "Error: command not found" >&2
+              exit -9
 fi
diff --git a/reverse b/reverse
--- a/reverse
+++ b/reverse
@@ -1,9 +1,18 @@
 #!/bin/bash
 
-if ![[ -f $1 ]]
+if ! [[ -f $1 ]]
 then
 echo "Error: no such file" >&2
 exit -6
+   elif [[ $1 = $2 ]]
+   then
+   echo "Error: the file names match" >&2
+   exit -11
+     elif [[ "$#" -ne 2 ]]
+     then
+     echo "Error: not enough arguments" >&2
+     exit -10
+        else
+        tac $1 > $2
 fi
 
-tac $1 > $2
diff --git a/strlen b/strlen
--- a/strlen
+++ b/strlen
@@ -1,4 +1,10 @@
 #!/bin/bash
 
 size=${#1}
+if [[ $size = 0 ]]
+then
+echo "Error: empty string" >&2
+exit -8
+else
 echo "$size"
+fi
