fixed x100000

diff --git a/menu b/menu
--- a/menu
+++ b/menu
@@ -55,5 +55,8 @@ elif
 [[ "$enter" = "g" ]] || [[ "$enter" = "Help" ]]
 then
 ./help
+else
+echo "Error: command not found" >&2
+exit -9
 fi
 done
diff --git a/reverse b/reverse
--- a/reverse
+++ b/reverse
@@ -4,15 +4,15 @@ if ! [[ -f $1 ]]
 then
 echo "Error: no such file" >&2
 exit -6
-   elif [[ $1 = $2 ]]
-   then
-   echo "Error: the file names match" >&2
-   exit -11
      elif [[ "$#" -ne 2 ]]
      then
      echo "Error: not enough arguments" >&2
      exit -10
-        else
-        tac $1 > $2
+        elif [[ -r $1 && -w $2 ]]
+          then
+	   tac $1 >> $2
+	else
+	   echo "Error: permission denied" >&2
+           exit -8
 fi
 
