fixed x100000

diff --git a/reverse b/reverse
--- a/reverse
+++ b/reverse
@@ -8,11 +8,24 @@ exit -6
      then
      echo "Error: not enough arguments" >&2
      exit -10
-        elif [[ -r $1 && -w $2 ]]
+else
+ if [[ -e $2 ]]
+   then
+	   if [[ -r $1 && -w $2 ]]
+           then
+	    tac $1 > $2
+	   else
+	    echo "Error: permission denied" >&2
+            exit -8
+	  fi
+        else
+          touch $2
+          if [[ -r $1 ]]
           then
-	   tac $1 >> $2
-	else
+	    tac $1 > $2
+          else
 	   echo "Error: permission denied" >&2
-           exit -8
+          fi
+	fi
 fi
 
